services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://jinxed:helpdesk@db:3306/helpdesk
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local_network
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/package.json

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: helpdesk
      MYSQL_USER: jinxed
      MYSQL_PASSWORD: helpdesk
      MYSQL_ROOT_PASSWORD: helpdesk
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - local_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  db-viewer:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: helpdesk
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  db_data:
